[package]
name = "df-rts"
version = "0.1.0"
authors = ["Kirill Vilkov <wide.wrd@gmail.com>"]

[dependencies]
glium = "*"
cgmath = "*"
image = "*"
assimp = "0.3.1"
enum-map = "*"
enum-map-derive = "*"
